config/routes.rb
JournalDemo::Application.routes.draw do
  get "sessions/new"
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :posts, :only => [:create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/login',  :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  root :to => 'pages#home'
  match '/about',   :to => 'pages#about'
  match '/privacy',   :to => 'pages#privacy'
  match '/faq',   :to => 'pages#faq'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user

  validates :content, :presence => true
  validates :user_id, :presence => true

  default_scope :order => 'posts.created_at DESC'
  
  comma do  # implicitly named :default
    id
    created_at
    content
  end

end

app/models/user.rb
# == Schema Information
# Schema version: 20100731203905
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password
  
  has_many :posts, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
    :length   => { :maximum => 50 }

  validates :email, :presence   => true,
    :format     => { :with => email_regex },
    :uniqueness => { :case_sensitive => false }

  validates :password, :presence  => true,
    :length    => { :maximum => 50 }


  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  def feed
    # This is preliminary. See Chapter 12 for the full implementation.
    Post.where("user_id = ?", id)
  end
  
  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if logged_in?
      @post = Post.new
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def about
    @title = "About"
  end

  def faq
    @title = "FAQ"
  end

  def privacy
    @title = "Privacy"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy

  def create
    @post  = current_user.posts.build(params[:post])
    if @post.save
      flash[:success] = "post created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end

  def destroy
    @post.destroy
    redirect_back_or root_path
  end

  private

    def authorized_user
      @post = Post.find(params[:id])
      redirect_to root_path unless current_user?(@post.user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Log In"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Log In"
      render 'new'
    else
      log_in user
      redirect_to root_path
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    respond_to do |format|
      format.xml { render :xml => @posts}
      format.html { render :csv => @posts}
    end
  end

  def new
    @user = User.new
    @title = "Sign Up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign Up"
      render 'new'
    end
  end

  def edit
    @title = "Edit User"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit User"
      render 'edit'
    end
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Journl | Definitely not a blog."
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def authenticate
    deny_access unless logged_in?
  end

  def deny_access
    store_location
    redirect_to login_path, :notice => "Please log in to access this page."
  end
  
  def current_user?(user)
    user == current_user
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def clear_return_to
    session[:return_to] = nil
  end
  
  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = stylesheet_link_tag 'reset.css', :media => 'screen'
    = stylesheet_link_tag 'screen.css', :media => 'screen'
    /[if lt IE 9]
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    = javascript_include_tag :defaults    
    = csrf_meta_tag
  %body
    .container
      %header
        %h2 Journl
        %nav.round
          %ul
            %li= link_to "Home", root_path
            %li= link_to "About", about_path
            - if logged_in?
              %li= link_to "Settings", edit_user_path(current_user)
            - if logged_in?
              %li= link_to "Log Out", logout_path, :method => :delete
            - else
              %li= link_to "Log In", login_path
      #content.round
        - flash.each do |key, value|
          %div{:class => "flash #{key}"}= value
        = yield
      %footer
        %nav.round
          %ul
            %li= link_to "About", about_path
            %li= link_to "FAQ", faq_path
            %li= link_to "Privacy", privacy_path
            %li
              %a{:href => "http://news.railstutorial.org/"} Support
      = debug(params) if Rails.env.development?        

app/views/pages/about.html.haml
%h1 About Us
%p
  %a{:href => "http://railstutorial.org/"} Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development
  with
  = succeed "." do
    %a{:href => "http://rubyonrails.org/"} Ruby on Rails
  This
  is the sample application for the tutorial.

app/views/pages/faq.html.haml
%h1 FAQ
%p
  This is the FAQ

app/views/pages/home.html.haml
- if logged_in?
  .front{:summary => "For logged-in users"}
    .main
      %h3.post Write a new entry.
      = render 'shared/post_form'
      = render 'shared/feed'
    .sidebar.round
      = render 'shared/user_info'
- else
  %h1 Sample App
  %p
    This is the home page for the
    %a{:href => "http://railstutorial.org/"} Ruby on Rails Tutorial
    sample application.
  = link_to "Sign up now!", signup_path, :class => "signup_button round"

app/views/pages/privacy.html.haml
%h1 Privacy Policy
%p
  This is the Privacy Policy

app/views/posts/_post.html.haml
.post
  .content= post.content
  %h4.timestamp
    Posted #{time_ago_in_words(post.created_at)} ago.

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    %h2
      = pluralize(object.errors.count, "error")
      prohibited this user from being saved:
    %p There were problems with the following fields:
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feed.html.haml
- unless @feed_items.empty?
  .posts{:summary => "User posts"}
    = render :partial => 'shared/feed_item', :collection => @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.haml
.post
  %h4
    #{feed_item.created_at.strftime("%d %B %Y")}
  .content= feed_item.content 
    
- if current_user?(feed_item.user)
  /= link_to "delete", feed_item, :method => :delete, |
  /  :confirm => "Are you sure?",                         |
  /  :title => feed_item.content                      |

app/views/shared/_post.html.haml
.post
  .content= post.content
  %h4.timestamp
    Posted #{time_ago_in_words(post.created_at)} ago.
- user = post.user rescue User.find(post.user_id)

- if current_user?(user)

  /= link_to "delete", post, :method => :delete, |
  /  :confirm => "Are you sure?",                |
  /  :title => post.content                      |

app/views/shared/_post_form.html.haml
= form_for @post do |f|
  = render 'shared/error_messages', :object => f.object
  %h4.timestamp
    #{Time.now.strftime("%B %d %Y %I:%M %p")}
  .field
    = f.text_area :content
  .actions
    = f.submit "Submit"

app/views/shared/_user_info.html.haml
.user_info
  %a{:href => user_path(current_user)}
    %span.user_name
      = current_user.name
    %span.posts
      = pluralize(current_user.posts.count, "post")

app/views/users/edit.html.haml
%h1 Edit user
= form_for(@user) do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .actions
    = f.submit "Update"
  .export
    = link_to "Export Posts to CSV", current_user
  

app/views/users/new.html.haml
%h1 Sign up
= form_for(@user) do |f|
  = render 'shared/error_messages'
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
  .actions
  = f.submit "Sign Up"